### ISSUE TITLE
React.createClass Deprecation warning

### ISSUE THREAD

**Issue by McPo** [donavon/react-router-relative-link#5]
The following warning is printed when used with react@15.5.4, however it still works fine but would be good to get it removed.

> ...../node_modules/fbjs/lib/warning.js:36Warning: Link: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.

**Comment by donavon** [comment]
fixed in v4.0.0
